name: PR-Arena with OpenHands

on:
  workflow_dispatch:
    inputs:
      issue_number:
        required: true
        type: number
      llm_models:
        required: true
        type: string
      llm_api_key:
        required: false
        type: string
        default: ''
      firebase_config:
        required: true
        type: string
      base_url:
        required: true
        type: string
      pat_token:
        required: true
        type: string
      pat_username:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set LLM_API_KEY from input or secrets
        run: |
          if [ -z "${{ inputs.llm_api_key }}" ]; then
            echo "LLM_API_KEY=${{ secrets.LLM_API_KEY }}" >> $GITHUB_ENV
          else
            echo "LLM_API_KEY=${{ inputs.llm_api_key }}" >> $GITHUB_ENV
          fi

      - name: Check required environment variables
        env:
          LLM_MODELS: ${{ inputs.llm_models }}
          LLM_API_KEY: ${{ env.LLM_API_KEY }}
          LLM_BASE_URL: ${{ inputs.base_url }}
          PAT_TOKEN: ${{ inputs.pat_token }}
          PAT_USERNAME: ${{ inputs.pat_username }}
        run: |
          required_vars=("LLM_MODELS" "LLM_API_KEY" "PAT_TOKEN" "PAT_USERNAME" "LLM_BASE_URL")
          for var in "${required_vars[@]}"; do
            if [ -z "${!var}" ]; then
              echo "Error: Required environment variable $var is not set."
              exit 1
            fi
          done

      - name: Set issue number
        run: echo "ISSUE_NUMBER=${{ inputs.issue_number }}" >> $GITHUB_ENV

      - name: Comment on issue with start message
        uses: actions/github-script@v7
        with:
          github-token: ${{ inputs.pat_token }}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ env.ISSUE_NUMBER }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `OpenHands started fixing the issue! You can monitor the progress [here](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}).`
            });

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/neulab/pr-arena.git@main
          pip install firebase-admin

      - name: Attempt to resolve issues and send the resolver output to Firebase
        env:
          GITHUB_TOKEN: ${{ inputs.pat_token }}
          LLM_MODELS: ${{ inputs.llm_models }}
          LLM_API_KEY: ${{ env.LLM_API_KEY }}
          LLM_BASE_URL: ${{ inputs.base_url }}
          PYTHONPATH: ""
          FIREBASE_CONFIG: ${{ inputs.firebase_config }}
        run: |
          cd /tmp && python -m openhands_resolver.resolve_issues \
            --repo ${{ github.repository }} \
            --issue-numbers ${{ env.ISSUE_NUMBER }}

      - name: Check resolution results
        id: check_results
        run: |
          if cd /tmp && grep -q '"success":true' output/output1.jsonl; then
            echo "MODEL1_RESOLUTION_SUCCESS=true" >> $GITHUB_ENV
          else
            echo "MODEL1_RESOLUTION_SUCCESS=false" >> $GITHUB_ENV
          fi
          if cd /tmp && grep -q '"success":true' output/output2.jsonl; then
            echo "MODEL2_RESOLUTION_SUCCESS=true" >> $GITHUB_ENV
          else
            echo "MODEL2_RESOLUTION_SUCCESS=false" >> $GITHUB_ENV
          fi
      
      - name: Post webpage link to GitHub issue comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ inputs.pat_token }}
          script: |
            const issueNumber = ${{ env.ISSUE_NUMBER }};
            const repo = context.repo.repo
            const owner = context.repo.owner
            const firebaseWebpageURL = `https://pr-arena.web.app/${owner}-${repo}-${issueNumber}`;

            github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `⚔️PR-Arena is now open⚔️! You can view the proposed fixes and make a decision at [this link](${firebaseWebpageURL}).`
            });
      
      - name: Wait for user's decision and save it to the GitHub environment
        env:
          GITHUB_TOKEN: ${{ inputs.pat_token }}
          LLM_MODELS: ${{ inputs.llm_models }}
          LLM_API_KEY: ${{ env.LLM_API_KEY }}
          LLM_BASE_URL: ${{ inputs.base_url }}
          GITHUB_USERNAME: ${{ inputs.pat_username }}
          PYTHONPATH: ""
          FIREBASE_CONFIG: ${{ inputs.firebase_config }}
        run: |
          cd /tmp && python -m openhands_resolver.listen_for_decision \
            --repo ${{ github.repository }} \
            --issue-number ${{ env.ISSUE_NUMBER }}
          

      - name: Create Pull Request for the selected branch
        env:
          GITHUB_TOKEN: ${{ inputs.pat_token }}
          LLM_MODELS: ${{ inputs.llm_models }}
          LLM_API_KEY: ${{ env.LLM_API_KEY }}
          LLM_BASE_URL: ${{ inputs.base_url }}
          PYTHONPATH: ""
          SELECTED_MODEL: ${{ env.SELECTED }}
        run: |
          cd /tmp && python -m openhands_resolver.send_pull_request \
            --issue-number ${{ env.ISSUE_NUMBER }} \
            --model-number $SELECTED_MODEL \
            --pr-type draft | tee pr_result${SELECTED_MODEL}.txt && \
            grep "draft created" pr_result${SELECTED_MODEL}.txt | sed 's/.*\///g' > pr_number.txt

      - name: Comment on issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ inputs.pat_token }}
          script: |
            const fs = require('fs');
            const issueNumber = ${{ env.ISSUE_NUMBER }};
            
            let prNumber = '';
            let branchName = '';
            
            try {
              prNumber = fs.readFileSync('/tmp/pr_number.txt', 'utf8').trim();
              } catch (error) {
                console.error('Error reading file:', error);
              }
            
            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `A potential fix has been generated and a draft PR #${prNumber} has been created. Please review the changes.`
              });
