name: PR-Arena with OpenHands

on:
  workflow_dispatch:
    inputs:
      issue_number:
        required: true
        type: number
      llm_models:
        required: true
        type: string
      llm_api_key:
        required: false
        type: string
        default: ''
      firebase_config:
        required: true
        type: string
      base_url:
        required: true
        type: string
      pat_token:
        required: true
        type: string
      pat_username:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set LLM_API_KEY from input or secrets
        run: |
          if [ -z "${{ inputs.llm_api_key }}" ]; then
            echo "LLM_API_KEY=${{ secrets.LLM_API_KEY }}" >> $GITHUB_ENV
          else
            echo "LLM_API_KEY=${{ inputs.llm_api_key }}" >> $GITHUB_ENV
          fi

      - name: Set issue number
        run: echo "ISSUE_NUMBER=${{ inputs.issue_number }}" >> $GITHUB_ENV

      - name: Comment on issue with start message
        uses: actions/github-script@v7
        with:
          github-token: ${{ inputs.pat_token }}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ env.ISSUE_NUMBER }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `OpenHands started fixing the issue! You can monitor the progress [here](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}).`
            });

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/neulab/pr-arena.git@main
          pip install firebase-admin

      - name: Attempt to resolve issues and send the resolver output to Firebase
        env:
          PYTHONPATH: ""
        run: |
          cd /tmp && python -m openhands_resolver.resolve_issues \
            --repo ${{ github.repository }} \
            --issue-numbers ${{ env.ISSUE_NUMBER }} \
            --token ${{ inputs.pat_token }} \
            --llm-models ${{ inputs.llm_models }} \
            --llm-api-key ${{ env.LLM_API_KEY }} \
            --llm-base-url ${{ inputs.base_url }} \
            --firebase-config ${{ inputs.firebase_config }}

      - name: Post webpage link to GitHub issue comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ inputs.pat_token }}
          script: |
            const issueNumber = ${{ env.ISSUE_NUMBER }};
            const repo = context.repo.repo
            const owner = context.repo.owner
            const firebaseWebpageURL = `https://pr-arena.web.app/${owner}-${repo}-${issueNumber}`;

            github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `⚔️PR-Arena is now open⚔️! You can view the proposed fixes and make a decision at [this link](${firebaseWebpageURL}).`
            });
      
      - name: Wait for user's decision and save it to the GitHub environment
        env:
          PYTHONPATH: ""
        run: |
          cd /tmp && python -m openhands_resolver.listen_for_decision \
            --repo ${{ github.repository }} \
            --issue-number ${{ env.ISSUE_NUMBER }} \
            --token ${{ inputs.pat_token }} \
            --username ${{ inputs.pat_username }} \
            --firebase-config ${{ inputs.firebase_config }}

      - name: Create Pull Request for the selected branch
        env:
          PYTHONPATH: ""
          SELECTED_MODEL: ${{ env.SELECTED }}
        run: |
          cd /tmp && python -m openhands_resolver.send_pull_request \
            --issue-number ${{ env.ISSUE_NUMBER }} \
            --model-number $SELECTED_MODEL \
            --pr-type draft \
            --token ${{ inputs.pat_token }} | tee pr_result${SELECTED_MODEL}.txt && \
            grep "draft created" pr_result${SELECTED_MODEL}.txt | sed 's/.*\///g' > pr_number.txt

      - name: Comment on issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ inputs.pat_token }}
          script: |
            const fs = require('fs');
            const issueNumber = ${{ env.ISSUE_NUMBER }};
            
            let prNumber = '';
            let branchName = '';
            
            try {
              prNumber = fs.readFileSync('/tmp/pr_number.txt', 'utf8').trim();
              } catch (error) {
                console.error('Error reading file:', error);
              }
            
            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `A potential fix has been generated and a draft PR #${prNumber} has been created. Please review the changes.`
              });
